"""empty message

Revision ID: 1e419568b223
Revises: 476f5d8b6cca
Create Date: 2016-04-28 11:49:48.742534

"""

# revision identifiers, used by Alembic.
revision = '1e419568b223'
down_revision = '476f5d8b6cca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer_file', sa.Column('layer_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer_file', 'layer_name')
    ### end Alembic commands ###
