"""empty message

Revision ID: 3bf825ecdb75
Revises: None
Create Date: 2016-04-26 19:38:44.989906

"""

# revision identifiers, used by Alembic.
revision = '3bf825ecdb75'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layer_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('geojson', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layer_file')
    ### end Alembic commands ###
