"""empty message

Revision ID: 476f5d8b6cca
Revises: 3bf825ecdb75
Create Date: 2016-04-27 16:18:00.093745

"""

# revision identifiers, used by Alembic.
revision = '476f5d8b6cca'
down_revision = '3bf825ecdb75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layer_file', 'geojson')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer_file', sa.Column('geojson', sa.TEXT(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
