"""empty message

Revision ID: 48ba1f90c512
Revises: 1e419568b223
Create Date: 2016-04-28 14:25:41.507356

"""

# revision identifiers, used by Alembic.
revision = '48ba1f90c512'
down_revision = '1e419568b223'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
